# https://hub.docker.com/_/python
FROM python:latest

ENV PYTHONUNBUFFERED True
ENV APP_HOME /api
ARG URL
ENV URL=${URL}
WORKDIR $APP_HOME
COPY . ./

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
